name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Matrix Demo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: build
        run: npm run build

        
 
       
