name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the deployment"
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: "The result of the deployment"
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        uses: echo "Deploying & Uploading..."
      - name: Set Result output
        id: step-result
        uses: echo "step-result=success"
